program: train.py
method: grid
metric:
  name: eval/macro_f1
  goal: maximize
parameters:
  features:
    values:
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, RHO_DIPOLE, PHI_DIPOLE, THETA_DIPOLE]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, BX_DIPOLE, BY_DIPOLE, BZ_DIPOLE, BABS_DIPOLE]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, RHO, RXY]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, X, Y, Z, D]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, VX, VY, VZ, VABS]
      - [BX_MSO, BY_MSO, BZ_MSO, X_MSO, Y_MSO, Z_MSO, DBX_MSO, DBY_MSO, DBZ_MSO, COSALPHA]
