# data split
train_orbits: 0.10
eval_orbits: 0.10
seed: 42

# optimization
batch_size: 1024
learning_rate: 0.0001
optimizer: Adam

# regularization
dropout_rate: 0.5
batch_normalization: True
early_stopping: True
patience: 5

# model
model_arch: MLP

# task params
window_size: 60
future_size: 10
features:
- X_MSO
- Y_MSO
- Z_MSO
- BX_MSO
- BY_MSO
- BZ_MSO
- DBX_MSO
- DBY_MSO
- DBZ_MSO

# linear params
hidden_layers: 2
hidden_size0: 256
hidden_size1: 256
hidden_size2: 128

# convolutional params
conv_layers: 3
channel_size0: 64
channel_size1: 64
channel_size2: 64
channel_size3: 64
channel_size4: 64
kernel_size0: 3
kernel_size1: 5
kernel_size2: 7
kernel_size3: 3
kernel_size4: 3
dilation_size0: 1
dilation_size1: 1
dilation_size2: 1
dilation_size3: 1
dilation_size4: 1
stride_size0: 1
stride_size1: 1
stride_size2: 1
stride_size3: 1
stride_size4: 1
pool_size0: 1
pool_size1: 1
pool_size2: 1
pool_size3: 1
pool_size4: 1

# recurrent params
rnn_layers: 2
state_size0: 32
state_size1: 32

# attentional params
attn_layers: 3
attn_size0: 128
attn_size1: 128
attn_size2: 128
attn_size3: 32
attn_size4: 32
head_size0: 4
head_size1: 4
head_size2: 4
head_size3: 4
head_size4: 4
