# data split
train_orbits: 1
eval_orbits: 1
seed: 42

# optimization
batch_size: 1024
learning_rate: 0.00001
optimizer: Adam

# regularization
dropout_rate: 0
batch_normalization: False
early_stopping: True
patience: 3

# model
model_arch: CRNN

# task params
window_size: 120
future_size: 20
features:
- X_MSO
- Y_MSO
- Z_MSO
- BX_MSO
- BY_MSO
- BZ_MSO
- DBX_MSO
- DBY_MSO
- DBZ_MSO

# linear params
hidden_layers: 2
hidden_size0: 128
hidden_size1: 128

# convolutional params
conv_layers: 3
channel_size0: 128
channel_size1: 128
channel_size2: 128
kernel_size0: 3
kernel_size1: 5
kernel_size2: 7
dilation_size0: 1
dilation_size1: 1
dilation_size2: 1
stride_size0: 1
stride_size1: 1
stride_size2: 1
pool_size0: 1
pool_size1: 1
pool_size2: 1

# recurrent params
rnn_layers: 2
state_size0: 32
state_size1: 32

# attentional params
attn_layers: 2
attn_size0: 64
attn_size1: 64
head_size0: 4
head_size1: 4
