batch_size: 4096
eval_split: 0.3
features:
- X_MSO
- Y_MSO
- Z_MSO
- BX_MSO
- BY_MSO
- BZ_MSO
- DBX_MSO
- DBY_MSO
- DBZ_MSO
future_size: 10
hidden_layers: 3
hidden_size0: 64
hidden_size1: 64
hidden_size2: 64
learning_rate: 0.001
model_arch: BaseNet
optimizer: Adam
seed: 1337
use_orbits: 0.05
window_size: 30
