max_epochs: 100
num_workers: 28
wandb_dir: /root/
wandb_enabled: true
wandb_entity: nelorth
wandb_group: crnn_full
wandb_notes: 0601 with fixed kernels, no dropout and larger channels
wandb_project: freddie